### ISSUE TITLE
Night CI 2024-01-02: Failed -- timeout to create daemonset

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#1126]
action url: https://github.com/spidernet-io/egressgateway/actions/runs/7389978991

**Comment by bzsuni** [comment]
```
• [FAILED] [20.375 seconds]
Reliability [Reliability]
/home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_test.go:31
  Test the drift of the EIP [BeforeEach]
  /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_test.go:44
    restart components [R00007]
    /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_test.go:224
      restart etcd
      /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_test.go:294

  Timeline >>
  > Enter [BeforeEach] Test the drift of the EIP - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_test.go:44 @ 01/02/24 21:11:11.816
  succeeded to create the gateway: egw-33f6325f-8c33-43c1-9a9b-b60e22d4d5ee
  v4DefaultEip: 172.18.2.5, v6DefaultEip: fc00:f853:ccd:e793::204
  Automatically polling progress:
    Reliability Test the drift of the EIP restart components restart etcd (Spec Runtime: 20.001s)
      /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_test.go:294
      In [BeforeEach] (Node Runtime: 20.001s)
        /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_test.go:44

      Spec Goroutine
      goroutine 4789 [sleep]
        time.Sleep(0x1dcd6500)
          /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/time.go:195
        github.com/spidernet-io/egressgateway/test/e2e/common.CreateDaemonSet({0x296fc10, 0xc0000501c8}, {0x29777e0, 0xc000690000}, {0xc000925b78, 0x13}, {0xc000046246, 0x2e})
          /home/runner/work/egressgateway/egressgateway/test/e2e/common/ds.go:71
      > github.com/spidernet-io/egressgateway/test/e2e/reliability_test.glob..func3.1.1()
          /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_test.go:70
            | 
            | // daemonSet
            > daemonSet, err = common.CreateDaemonSet(ctx, cli, "ds-reliability-"+faker.Word(), config.Image)
            | Expect(err).NotTo(HaveOccurred())
            | GinkgoWriter.Printf("succeeded to create DaemonSet: %s\n", daemonSet.Name)
        github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x0, 0xc0007b2180})
          /home/runner/work/egressgateway/egressgateway/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463
        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
          /home/runner/work/egressgateway/egressgateway/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:889
        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode
          /home/runner/work/egressgateway/egressgateway/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:876
  [FAILED] Unexpected error:
      <*errors.errorString | 0xc000775740>: 
      create DaemonSet time out
      {
          s: "create DaemonSet time out",
      }
  occurred
  In [BeforeEach] at: /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_test.go:71 @ 01/02/24 21:11:32.016
```
