### ISSUE TITLE
Night CI 2024-02-04: Failed -- egp not found

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#1196]
action url: https://github.com/spidernet-io/egressgateway/actions/runs/7776411155

**Comment by bzsuni** [comment]
```
• [FAILED] [202.664 seconds]
IP Allocation [Reliability_IP]
/home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:21
  [It] test IP allocation [R00008, P00009]
  /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:71

  Timeline >>
  > Enter [BeforeEach] IP Allocation - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:36 @ 02/04/24 20:53:23.217
  succeeded create egw: egw-a1baaa71-71e2-4cd2-b057-a538df1d6a5d
  < Exit [BeforeEach] IP Allocation - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:36 @ 02/04/24 20:53:26.911 (3.694s)
  > Enter [It] test IP allocation - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:71 @ 02/04/24 20:53:26.912
  STEP: create egressPolicies by gaven pods - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:73 @ 02/04/24 20:53:26.912
  Automatically polling progress:
    IP Allocation test IP allocation (Spec Runtime: 23.695s)
      /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:71
      In [It] (Node Runtime: 20s)
        /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:71
        At [By Step] create egressPolicies by gaven pods (Step Runtime: 20s)
          /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:73

        Spec Goroutine
        goroutine 1405 [sleep]
          time.Sleep(0x1dcd6500)
            /opt/hostedtoolcache/go/1.20.5/x64/src/runtime/time.go:195
          github.com/spidernet-io/egressgateway/test/e2e/common.WaitEgressPolicyStatusReady({0x2973030, 0xc0000501b8}, {0x297ac00, 0xc000206510}, 0xc00045da40, 0x1, 0x1, 0xc0009d5da9?)
            /home/runner/work/egressgateway/egressgateway/test/e2e/common/egp.go:320
          github.com/spidernet-io/egressgateway/test/e2e/common.CreateEgressPoliciesForPods({0x2973030, 0xc0000501b8}, {0x297ac00?, 0xc000206510}, 0x4938d1?, {0xc000289a00, 0x32, 0x0?}, 0x6?, 0x1, ...)
            /home/runner/work/egressgateway/egressgateway/test/e2e/common/egp.go:393
        > github.com/spidernet-io/egressgateway/test/e2e/reliability_test.glob..func1.2()
            /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:74
              | // create egresspolicies
              | By("create egressPolicies by gaven pods")
              > egps, _, err = common.CreateEgressPoliciesForPods(ctx, cli, egw, pods, egressConfig.EnableIPv4, egressConfig.EnableIPv6, creationThresholdTime)
              | Expect(err).NotTo(HaveOccurred())
              | 
          github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x0, 0xc0007ab080})
            /home/runner/work/egressgateway/egressgateway/vendor/github.com/onsi/ginkgo/v2/internal/node.go:463
          github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
            /home/runner/work/egressgateway/egressgateway/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:889
          github.com/onsi/ginkgo/v2/internal.(*Suite).runNode
            /home/runner/work/egressgateway/egressgateway/vendor/github.com/onsi/ginkgo/v2/internal/suite.go:876
  STEP: create extra egressPolicies - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:77 @ 02/04/24 20:54:33.36
  STEP: delete all egressPolicies - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:88 @ 02/04/24 20:54:34.297
  STEP: create egressPolicies by gaven pods - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:93 @ 02/04/24 20:54:39.962
  STEP: create another extra egressPolicies - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:97 @ 02/04/24 20:55:44.095
  STEP: check egressgateway status synced with egresspolicies - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:107 @ 02/04/24 20:55:44.998
  STEP: check eip of pods - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:124 @ 02/04/24 20:55:46.191
  STEP: delete all egressPolicies - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:135 @ 02/04/24 20:55:49.405
  STEP: check egressgateway status should be empty - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:139 @ 02/04/24 20:55:58.407
  [FAILED] Unexpected error:
      <*errors.errorString | 0xc000625240>: 
      egressGateway failed synced with egressPolicy, error: egresspolicies.egressgateway.spidernet.io "egp-e67eeca4-3683-47fc-bf60-1a2481ee41c4" not found
      
      {
          s: "egressGateway failed synced with egressPolicy, error: egresspolicies.egressgateway.spidernet.io \"egp-e67eeca4-3683-47fc-bf60-1a2481ee41c4\" not found\n",
      }
  occurred
  In [It] at: /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:141 @ 02/04/24 20:56:28.784
  < Exit [It] test IP allocation - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:71 @ 02/04/24 20:56:28.785 (3m1.873s)
  > Enter [DeferCleanup (Each)] IP Allocation - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:46 @ 02/04/24 20:56:28.785
  < Exit [DeferCleanup (Each)] IP Allocation - /home/runner/work/egressgateway/egressgateway/test/e2e/reliability/reliability_ip_test.go:46 @ 02/04/24 20:56:45.881 (17.096s)
  << Timeline
```

**Comment by weizhoublue** [comment]
any update
