### ISSUE TITLE
Night CI 2023-10-21: Failed -- found a panic in the egressclusterinfo controller

### ISSUE THREAD

**Issue by weizhoublue** [spidernet-io/egressgateway#851]
action url: https://github.com/spidernet-io/egressgateway/actions/runs/6599373167

**Comment by bzsuni** [comment]
```
{"level":"info","ts":"2023-10-21T20:26:27.503Z","caller":"controller/controller.go:114","msg":"Observed a panic in reconciler: close of closed channel","controller":"egressClusterInfo","object":{"name":"default","namespace":"EGCI/"},"namespace":"EGCI/","name":"default","reconcileID":"c940e589-a72a-4f71-9599-3c4f8b756d74"}
panic: close of closed channel [recovered]
	panic: close of closed channel

goroutine 305 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:115 +0x2c5
panic({0x249be20, 0x2a307f0})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/spidernet-io/egressgateway/pkg/controller/egress_cluster_info.(*eciReconciler).stopAllCheckGoroutine(0xc00019e1a0)
	/src/pkg/controller/egress_cluster_info/egress_cluster_info.go:532 +0xca
github.com/spidernet-io/egressgateway/pkg/controller/egress_cluster_info.(*eciReconciler).reconcileEgressClusterInfo(0xc00019e1a0, {0x2a4b8d8, 0xc000a0d7a0}, {{{0xc000d0b90b?, 0xc000c520b0?}, {0xc00061e559?, 0x0?}}}, {{0x2a4dce8, 0xc000a0d7d0}, 0x0})
	/src/pkg/controller/egress_cluster_info/egress_cluster_info.go:192 +0x735
github.com/spidernet-io/egressgateway/pkg/controller/egress_cluster_info.(*eciReconciler).Reconcile(0xc00019e1a0, {0x2a4b8d8, 0xc000a0d7a0}, {{{0xc000d0b90b?, 0x30?}, {0xc00061e559?, 0x30?}}})
	/src/pkg/controller/egress_cluster_info/egress_cluster_info.go:117 +0x4b8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc000280320, {0x2a4b8d8, 0xc000a0d7a0}, {{{0xc000d0b90b?, 0x24149a0?}, {0xc00061e559?, 0x0?}}})
	/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:118 +0x16e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000280320, {0x2a4b830, 0xc0001eb950}, {0x251efa0?, 0xc000c76900?})
	/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:314 +0x4ac
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000280320, {0x2a4b830, 0xc0001eb950})
	/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:265 +0x325
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:226 +0xc9
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/src/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222 +0x807
```
